site_name: mindy.cc
theme:
  name: null
  custom_dir: themes/dracula
  # logo: assets/img/dracula.png
  # favicon: assets/img/favicon.ico
  # highlight_js: highlight.min.js
  # highlight_css: atom-one-dark.min.css
  # highlight_css: github.min.css

nav:
    - Home: index.md
    - More:
      - nav/settings/custom-highlight.md
